ip = '127.0.0.1'

[keys]
github = 'xxxxxxxxxxxxxxxxx'
travis = 'yyyyyyyyyyyyyyyyy'

[settings]
lark_bot_webhook = 'd7110b67-8010-441e-ab08-111'

lark_bot_webhook_1w = '6efb9cce-de5a-4b03-af8a-22'

lark_bot_webhook_1d = '3aff8180-8262-4f42-8fb1-33'

lark_bot_webhook_4h = '62f86e6d-5b75-4868-b620-44'